name: WakaTime Activity Update

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:  

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: "Updated WakaTime stats"
          TIME_RANGE: all_time  
